language: c++

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-6
            - gcc-6

git:
  submodules: false

script:
  - git submodule update --init --recursive
  - mkdir -p build
  - cd build
  - cmake ..
  - make -j2
